language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t achevsky/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true achevsky/react-test npm test 

after_success:
  - docker build -t achevsky/multi-client -f ./client/Dockerfile.dev ./client
  - docker build -t achevsky/multi-worker -f ./worker/Dockerfile.dev ./worker
  - docker build -t achevsky/multi-nginx -f ./ngnix/Dockerfile.dev ./nginx
  - docker build -t achevsky/multi-server -f ./server/Dockerfile.dev ./server

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push achevsky/multi-client
  - docker push achevsky/multi-server
  - docker push achevsky/multi-worker
  - docker push achevsky/multi-nginx