language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t alexchevsky/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alexchevsky/react-test npm test 

after_success:
  - docker build -t alexchevsky/multi-client -f ./client/Dockerfile.dev ./client
  - docker build -t alexchevsky/multi-worker -f ./client/Dockerfile.dev ./worder
  - docker build -t alexchevsky/multi-nginx -f ./client/Dockerfile.dev ./nginx
  - docker build -t alexchevsky/multi-server -f ./client/Dockerfile.dev ./server
