language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t achevsky/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true achevsky/react-test npm test 

after_success:
  - docker build -t achevsky/multi-client ./client
  - docker build -t achevsky/multi-server ./server
  - docker build -t achevsky/multi-worker ./worker
  - docker build -t achevsky/multi-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push achevsky/multi-client
  - docker push achevsky/multi-server
  - docker push achevsky/multi-worker
  - docker push achevsky/multi-nginx